#!/usr/bin/python3
def raise_exception():
    j = [1, 2, 3]
    i = int(j)
    print(i)
